version: 1.0.{build}
image: Visual Studio 2019

environment:
  TreatWarningsAsErrors: true

before_build:
- ps: >-
    dotnet restore

build:
  verbosity: minimal

artifacts:
- path: '**\*.dot'
  name: Files